export default [
  {
    inputs: [
      { internalType: 'address', name: '_poidhNft', type: 'address' },
      { internalType: 'address', name: '_treasury', type: 'address' },
      { internalType: 'uint256', name: '_startClaimIndex', type: 'uint256' },
      { internalType: 'uint256', name: '_minBountyAmount', type: 'uint256' },
      { internalType: 'uint256', name: '_minContribution', type: 'uint256' },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  { inputs: [], name: 'AlreadyVoted', type: 'error' },
  { inputs: [], name: 'BountyClaimed', type: 'error' },
  { inputs: [], name: 'BountyClosed', type: 'error' },
  { inputs: [], name: 'BountyNotFound', type: 'error' },
  { inputs: [], name: 'ClaimAlreadyAccepted', type: 'error' },
  { inputs: [], name: 'ClaimNotFound', type: 'error' },
  { inputs: [], name: 'ContractsCannotCreateBounties', type: 'error' },
  { inputs: [], name: 'DirectEtherNotAccepted', type: 'error' },
  { inputs: [], name: 'InsufficientBalance', type: 'error' },
  {
    inputs: [{ internalType: 'uint256', name: 'amount', type: 'uint256' }],
    name: 'InvalidMinBountyAmount',
    type: 'error',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'amount', type: 'uint256' }],
    name: 'InvalidMinContribution',
    type: 'error',
  },
  {
    inputs: [{ internalType: 'address', name: 'poidhNft', type: 'address' }],
    name: 'InvalidPoidhNft',
    type: 'error',
  },
  { inputs: [], name: 'InvalidStartClaimIndex', type: 'error' },
  {
    inputs: [{ internalType: 'address', name: 'treasury', type: 'address' }],
    name: 'InvalidTreasury',
    type: 'error',
  },
  {
    inputs: [{ internalType: 'address', name: 'to', type: 'address' }],
    name: 'InvalidWithdrawTo',
    type: 'error',
  },
  { inputs: [], name: 'IssuerCannotClaim', type: 'error' },
  { inputs: [], name: 'IssuerCannotWithdraw', type: 'error' },
  { inputs: [], name: 'MaxParticipantsReached', type: 'error' },
  { inputs: [], name: 'MinimumBountyNotMet', type: 'error' },
  { inputs: [], name: 'MinimumContributionNotMet', type: 'error' },
  { inputs: [], name: 'NoEther', type: 'error' },
  { inputs: [], name: 'NoVotingPeriodSet', type: 'error' },
  { inputs: [], name: 'NotActiveParticipant', type: 'error' },
  { inputs: [], name: 'NotCancelledOpenBounty', type: 'error' },
  { inputs: [], name: 'NotOpenBounty', type: 'error' },
  { inputs: [], name: 'NotSoloBounty', type: 'error' },
  { inputs: [], name: 'NothingToWithdraw', type: 'error' },
  { inputs: [], name: 'ReentrancyGuardReentrantCall', type: 'error' },
  { inputs: [], name: 'TransferFailed', type: 'error' },
  { inputs: [], name: 'VoteWouldPass', type: 'error' },
  { inputs: [], name: 'VotingEnded', type: 'error' },
  { inputs: [], name: 'VotingOngoing', type: 'error' },
  { inputs: [], name: 'WrongCaller', type: 'error' },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'bountyId',
        type: 'uint256',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'issuer',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'issuerRefund',
        type: 'uint256',
      },
    ],
    name: 'BountyCancelled',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'id', type: 'uint256' },
      {
        indexed: true,
        internalType: 'address',
        name: 'issuer',
        type: 'address',
      },
      { indexed: false, internalType: 'string', name: 'title', type: 'string' },
      {
        indexed: false,
        internalType: 'string',
        name: 'description',
        type: 'string',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'createdAt',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'bool',
        name: 'isOpenBounty',
        type: 'bool',
      },
    ],
    name: 'BountyCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'bountyId',
        type: 'uint256',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'participant',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'latestBountyBalance',
        type: 'uint256',
      },
    ],
    name: 'BountyJoined',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'bountyId',
        type: 'uint256',
      },
      {
        indexed: true,
        internalType: 'uint256',
        name: 'claimId',
        type: 'uint256',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'claimIssuer',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'bountyIssuer',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'bountyAmount',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'payout',
        type: 'uint256',
      },
      { indexed: false, internalType: 'uint256', name: 'fee', type: 'uint256' },
    ],
    name: 'ClaimAccepted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'id', type: 'uint256' },
      {
        indexed: true,
        internalType: 'address',
        name: 'issuer',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'uint256',
        name: 'bountyId',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'bountyIssuer',
        type: 'address',
      },
      { indexed: false, internalType: 'string', name: 'title', type: 'string' },
      {
        indexed: false,
        internalType: 'string',
        name: 'description',
        type: 'string',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'createdAt',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'string',
        name: 'imageUri',
        type: 'string',
      },
    ],
    name: 'ClaimCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'bountyId',
        type: 'uint256',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'participant',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
    ],
    name: 'RefundClaimed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'voter',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'uint256',
        name: 'bountyId',
        type: 'uint256',
      },
      {
        indexed: true,
        internalType: 'uint256',
        name: 'claimId',
        type: 'uint256',
      },
      { indexed: false, internalType: 'bool', name: 'support', type: 'bool' },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'weight',
        type: 'uint256',
      },
    ],
    name: 'VoteCast',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'bountyId',
        type: 'uint256',
      },
      {
        indexed: true,
        internalType: 'uint256',
        name: 'claimId',
        type: 'uint256',
      },
      { indexed: false, internalType: 'bool', name: 'passed', type: 'bool' },
      { indexed: false, internalType: 'uint256', name: 'yes', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'no', type: 'uint256' },
    ],
    name: 'VotingResolved',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'bountyId',
        type: 'uint256',
      },
      {
        indexed: true,
        internalType: 'uint256',
        name: 'claimId',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'deadline',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'issuerYesWeight',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'round',
        type: 'uint256',
      },
    ],
    name: 'VotingStarted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'bountyId',
        type: 'uint256',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'participant',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'latestBountyAmount',
        type: 'uint256',
      },
    ],
    name: 'WithdrawFromOpenBounty',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'user', type: 'address' },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
    ],
    name: 'Withdrawal',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'user', type: 'address' },
      { indexed: true, internalType: 'address', name: 'to', type: 'address' },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
    ],
    name: 'WithdrawalTo',
    type: 'event',
  },
  {
    inputs: [],
    name: 'BPS_DENOM',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'FEE_BPS',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MAX_PARTICIPANTS',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MIN_BOUNTY_AMOUNT',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MIN_CONTRIBUTION',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'bountyId', type: 'uint256' },
      { internalType: 'uint256', name: 'claimId', type: 'uint256' },
    ],
    name: 'acceptClaim',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'bounties',
    outputs: [
      { internalType: 'uint256', name: 'id', type: 'uint256' },
      { internalType: 'address', name: 'issuer', type: 'address' },
      { internalType: 'string', name: 'name', type: 'string' },
      { internalType: 'string', name: 'description', type: 'string' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
      { internalType: 'address', name: 'claimer', type: 'address' },
      { internalType: 'uint256', name: 'createdAt', type: 'uint256' },
      { internalType: 'uint256', name: 'claimId', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'bountyId', type: 'uint256' },
      { internalType: 'uint256', name: '', type: 'uint256' },
    ],
    name: 'bountyClaims',
    outputs: [{ internalType: 'uint256', name: 'claimIds', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'bountyCounter',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'bountyId', type: 'uint256' }],
    name: 'bountyCurrentVotingClaim',
    outputs: [{ internalType: 'uint256', name: 'claimId', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'bountyId', type: 'uint256' }],
    name: 'bountyVotingTracker',
    outputs: [
      { internalType: 'uint256', name: 'yes', type: 'uint256' },
      { internalType: 'uint256', name: 'no', type: 'uint256' },
      { internalType: 'uint256', name: 'deadline', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'bountyId', type: 'uint256' }],
    name: 'cancelOpenBounty',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'bountyId', type: 'uint256' }],
    name: 'cancelSoloBounty',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'claimCounter',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'bountyId', type: 'uint256' }],
    name: 'claimRefundFromCancelledOpenBounty',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'claims',
    outputs: [
      { internalType: 'uint256', name: 'id', type: 'uint256' },
      { internalType: 'address', name: 'issuer', type: 'address' },
      { internalType: 'uint256', name: 'bountyId', type: 'uint256' },
      { internalType: 'address', name: 'bountyIssuer', type: 'address' },
      { internalType: 'string', name: 'name', type: 'string' },
      { internalType: 'string', name: 'description', type: 'string' },
      { internalType: 'uint256', name: 'createdAt', type: 'uint256' },
      { internalType: 'bool', name: 'accepted', type: 'bool' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'bountyId', type: 'uint256' },
      { internalType: 'string', name: 'name', type: 'string' },
      { internalType: 'string', name: 'description', type: 'string' },
      { internalType: 'string', name: 'uri', type: 'string' },
    ],
    name: 'createClaim',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'string', name: 'name', type: 'string' },
      { internalType: 'string', name: 'description', type: 'string' },
    ],
    name: 'createOpenBounty',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'string', name: 'name', type: 'string' },
      { internalType: 'string', name: 'description', type: 'string' },
    ],
    name: 'createSoloBounty',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'bountyId', type: 'uint256' }],
    name: 'everHadExternalContributor',
    outputs: [
      { internalType: 'bool', name: 'hadExternalContributor', type: 'bool' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'offset', type: 'uint256' }],
    name: 'getBounties',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'id', type: 'uint256' },
          { internalType: 'address', name: 'issuer', type: 'address' },
          { internalType: 'string', name: 'name', type: 'string' },
          { internalType: 'string', name: 'description', type: 'string' },
          { internalType: 'uint256', name: 'amount', type: 'uint256' },
          { internalType: 'address', name: 'claimer', type: 'address' },
          { internalType: 'uint256', name: 'createdAt', type: 'uint256' },
          { internalType: 'uint256', name: 'claimId', type: 'uint256' },
        ],
        internalType: 'struct PoidhV3.Bounty[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'user', type: 'address' },
      { internalType: 'uint256', name: 'offset', type: 'uint256' },
    ],
    name: 'getBountiesByUser',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'id', type: 'uint256' },
          { internalType: 'address', name: 'issuer', type: 'address' },
          { internalType: 'string', name: 'name', type: 'string' },
          { internalType: 'string', name: 'description', type: 'string' },
          { internalType: 'uint256', name: 'amount', type: 'uint256' },
          { internalType: 'address', name: 'claimer', type: 'address' },
          { internalType: 'uint256', name: 'createdAt', type: 'uint256' },
          { internalType: 'uint256', name: 'claimId', type: 'uint256' },
        ],
        internalType: 'struct PoidhV3.Bounty[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getBountiesLength',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'bountyId', type: 'uint256' },
      { internalType: 'uint256', name: 'offset', type: 'uint256' },
    ],
    name: 'getClaimsByBountyId',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'id', type: 'uint256' },
          { internalType: 'address', name: 'issuer', type: 'address' },
          { internalType: 'uint256', name: 'bountyId', type: 'uint256' },
          { internalType: 'address', name: 'bountyIssuer', type: 'address' },
          { internalType: 'string', name: 'name', type: 'string' },
          { internalType: 'string', name: 'description', type: 'string' },
          { internalType: 'uint256', name: 'createdAt', type: 'uint256' },
          { internalType: 'bool', name: 'accepted', type: 'bool' },
        ],
        internalType: 'struct PoidhV3.Claim[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'user', type: 'address' },
      { internalType: 'uint256', name: 'offset', type: 'uint256' },
    ],
    name: 'getClaimsByUser',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'id', type: 'uint256' },
          { internalType: 'address', name: 'issuer', type: 'address' },
          { internalType: 'uint256', name: 'bountyId', type: 'uint256' },
          { internalType: 'address', name: 'bountyIssuer', type: 'address' },
          { internalType: 'string', name: 'name', type: 'string' },
          { internalType: 'string', name: 'description', type: 'string' },
          { internalType: 'uint256', name: 'createdAt', type: 'uint256' },
          { internalType: 'bool', name: 'accepted', type: 'bool' },
        ],
        internalType: 'struct PoidhV3.Claim[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'bountyId', type: 'uint256' }],
    name: 'getParticipants',
    outputs: [
      { internalType: 'address[]', name: '', type: 'address[]' },
      { internalType: 'uint256[]', name: '', type: 'uint256[]' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'bountyId', type: 'uint256' },
      { internalType: 'uint256', name: 'offset', type: 'uint256' },
      { internalType: 'uint256', name: 'limit', type: 'uint256' },
    ],
    name: 'getParticipantsPaged',
    outputs: [
      { internalType: 'address[]', name: 'addrs', type: 'address[]' },
      { internalType: 'uint256[]', name: 'amts', type: 'uint256[]' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'bountyId', type: 'uint256' }],
    name: 'joinOpenBounty',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'bountyId', type: 'uint256' },
      { internalType: 'uint256', name: '', type: 'uint256' },
    ],
    name: 'participantAmounts',
    outputs: [
      {
        internalType: 'uint256',
        name: 'participantContributionAmounts',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'bountyId', type: 'uint256' },
      { internalType: 'uint256', name: '', type: 'uint256' },
    ],
    name: 'participants',
    outputs: [
      {
        internalType: 'address',
        name: 'participantAddresses',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
    name: 'pendingWithdrawals',
    outputs: [{ internalType: 'uint256', name: 'amount', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'poidhNft',
    outputs: [
      { internalType: 'contract IPoidhClaimNFT', name: '', type: 'address' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'bountyId', type: 'uint256' }],
    name: 'resetVotingPeriod',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'bountyId', type: 'uint256' }],
    name: 'resolveVote',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'bountyId', type: 'uint256' },
      { internalType: 'uint256', name: 'claimId', type: 'uint256' },
    ],
    name: 'submitClaimForVote',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'treasury',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'user', type: 'address' },
      { internalType: 'uint256', name: '', type: 'uint256' },
    ],
    name: 'userBounties',
    outputs: [{ internalType: 'uint256', name: 'bountyIds', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'user', type: 'address' },
      { internalType: 'uint256', name: '', type: 'uint256' },
    ],
    name: 'userClaims',
    outputs: [{ internalType: 'uint256', name: 'claimIds', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'bountyId', type: 'uint256' },
      { internalType: 'bool', name: 'vote', type: 'bool' },
    ],
    name: 'voteClaim',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'bountyId', type: 'uint256' }],
    name: 'voteRound',
    outputs: [{ internalType: 'uint256', name: 'roundId', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'bountyId', type: 'uint256' },
      { internalType: 'address', name: 'participant', type: 'address' },
    ],
    name: 'voteWeightSnapshot',
    outputs: [{ internalType: 'uint256', name: 'weight', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'votingPeriod',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'withdraw',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'bountyId', type: 'uint256' }],
    name: 'withdrawFromOpenBounty',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address payable', name: 'to', type: 'address' }],
    name: 'withdrawTo',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  { stateMutability: 'payable', type: 'receive' },
] as const;
